#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : glproto
Version  : 1.4.17
Release  : 5
URL      : http://xorg.freedesktop.org/releases/individual/proto/glproto-1.4.17.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/proto/glproto-1.4.17.tar.gz
Summary  : GL extension headers
Group    : Development/Tools
License  : SGI-B-2.0

%description
OpenGL Extension to the X Window System
This extension defines a protocol for the client to send 3D rendering
commands to the X server.

%package dev
Summary: dev components for the glproto package.
Group: Development

%description dev
dev components for the glproto package.


%prep
%setup -q -n glproto-1.4.17

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/GL/glxint.h
/usr/include/GL/glxmd.h
/usr/include/GL/glxproto.h
/usr/include/GL/glxtokens.h
/usr/include/GL/internal/glcore.h
/usr/lib64/pkgconfig/*.pc
